// <auto-generated />
using System;
using Backend;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250129193734_v5")]
    partial class v5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.WeatherForecast", b =>
                {
                    b.Property<DateOnly>("date")
                        .HasColumnType("date");

                    b.Property<string>("summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("temperatureC")
                        .HasColumnType("int");

                    b.HasKey("date");

                    b.ToTable("forecast");
                });
#pragma warning restore 612, 618
        }
    }
}
